# Generated by Django 3.2.13 on 2022-06-02 00:32

from django.db import migrations, models
import mysql_compressed_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex: program.py', max_length=150)),
                ('content', mysql_compressed_fields.fields.CompressedTextField(blank=True, db_column='content_compressed', help_text="ex: print('Hello World!')")),
            ],
        ),
    ]
